import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Use — Amaia | BloomWave',
  description: 'Terms of use for Amaia by BloomWave.',
}

export default function AmaiaTermsPage() {
  return (
    <div className="pt-24 pb-16">
      <article className="max-w-3xl mx-auto px-6">
        <div className="mb-12">
          <Link
            href="/"
            className="text-sm text-forest-500 hover:text-forest-600 transition-colors"
          >
            &larr; Back to BloomWave
          </Link>
        </div>

        <h1 className="font-serif text-4xl md:text-5xl text-bark-600 mb-3">
          Terms of Use
        </h1>
        <p className="text-lg text-bark-300 mb-2">Amaia</p>
        <p className="text-sm text-bark-200 mb-12">
          Effective Date: March 19, 2026
        </p>

        <div className="prose-policy space-y-10 text-bark-500 leading-relaxed">
          {/* Agreement */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Agreement to Terms
            </h2>
            <p>
              By downloading, installing, or using Amaia (the &ldquo;App&rdquo;), you agree to be bound by these Terms of Use (&ldquo;Terms&rdquo;). If you do not agree to these Terms, do not use the App. These Terms constitute a legally binding agreement between you and BloomWave (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;).
            </p>
          </section>

          {/* Description */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Description of the App
            </h2>
            <p>
              Amaia is an AI companion app that remembers you across conversations. Through daily check-ins, personalized coaching, and meaningful dialogue, Amaia learns about your life, goals, and personality to provide guidance and companionship over time. The App is designed for personal wellness and self-reflection purposes. Amaia is not a licensed therapist, counselor, or medical professional and does not provide medical, psychological, or professional advice of any kind.
            </p>
          </section>

          {/* AI-Generated Content */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              AI-Generated Content
            </h2>
            <p>
              Amaia&rsquo;s responses are generated by artificial intelligence language models. While we strive for helpful, thoughtful, and accurate responses, AI-generated content may occasionally be inaccurate, incomplete, or inappropriate. You should not rely on Amaia&rsquo;s responses as a substitute for professional advice, including but not limited to medical, legal, financial, or mental health guidance.
            </p>
            <p className="mt-3">
              If you are experiencing a mental health crisis, please contact a qualified professional, call 988 (Suicide &amp; Crisis Lifeline), or go to your nearest emergency room. Amaia is not equipped to handle emergencies.
            </p>
          </section>

          {/* Gem Purchases */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Gem Purchases &amp; Payments
            </h2>
            <p className="mb-3">
              Amaia uses a gem-based system. Each message you send costs one gem. You receive free gems daily and may purchase additional gems through in-app purchases.
            </p>
            <ul className="list-disc pl-5 space-y-1 text-sm">
              <li>Gem purchases are one-time, non-recurring transactions (not subscriptions).</li>
              <li>Gems are consumable digital items and are non-refundable once purchased, except as required by applicable law or Apple&rsquo;s refund policies.</li>
              <li>Gems have no monetary value outside the App and cannot be exchanged, transferred, or redeemed for cash.</li>
            </ul>
            <p className="mt-3">
              All payments are processed through Apple&rsquo;s App Store via In-App Purchases. We do not directly collect or store your payment information. Prices are displayed in your local currency and may vary by region. We reserve the right to change gem pricing or the number of gems included in each package at any time.
            </p>
          </section>

          {/* User Content */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Your Content &amp; Amaia&rsquo;s Memory
            </h2>
            <p>
              You retain ownership of all content you provide through the App, including messages, check-in entries, and personal information you share. By using the App, you grant us a limited license to store, process, and transmit your content solely for the purpose of providing and improving the service.
            </p>
            <p className="mt-3">
              Amaia builds a memory of details you share across conversations. You can view, correct, delete specific memories, or reset Amaia&rsquo;s memory entirely at any time from within the App. Your conversation history and memories are private and visible only to you.
            </p>
          </section>

          {/* Acceptable Use */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Acceptable Use
            </h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 text-sm">
              <li>Use the App for any unlawful purpose or in violation of any applicable laws</li>
              <li>Attempt to manipulate Amaia into generating harmful, illegal, or explicitly sexual content</li>
              <li>Use the App if you are under 18 years of age</li>
              <li>Attempt to reverse engineer, decompile, or disassemble any part of the App</li>
              <li>Interfere with or disrupt the App&rsquo;s functionality or servers</li>
              <li>Use the App to harass, abuse, or harm another person</li>
              <li>Reproduce, distribute, or create derivative works from the App&rsquo;s content without our written permission</li>
            </ul>
          </section>

          {/* Age Requirement */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Age Requirement
            </h2>
            <p>
              You must be at least 18 years old to use Amaia. By using the App, you represent and warrant that you are at least 18 years of age. We do not knowingly collect personal information from anyone under 18. If we learn that we have collected personal information from a user under 18, we will take steps to delete that information promptly.
            </p>
          </section>

          {/* Intellectual Property */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Intellectual Property
            </h2>
            <p>
              All content in the App, including but not limited to text, graphics, images, icons, persona designs, and the overall design, is owned by or licensed to BloomWave and is protected by copyright and other intellectual property laws. You may not copy, modify, distribute, or create derivative works from any App content without our prior written consent.
            </p>
          </section>

          {/* Disclaimers */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Disclaimers
            </h2>
            <p>
              The App is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, either express or implied. We do not warrant that the App will be uninterrupted, error-free, or free of harmful components.
            </p>
            <p className="mt-3">
              Amaia is an AI companion designed for personal reflection, emotional support, and general wellness guidance. It is not a substitute for professional therapy, counseling, or medical treatment. We make no guarantees regarding the accuracy, completeness, or appropriateness of any AI-generated response.
            </p>
          </section>

          {/* Limitation of Liability */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by applicable law, BloomWave shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from your use of the App, including but not limited to any actions taken or not taken based on AI-generated content.
            </p>
          </section>

          {/* Termination */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Termination
            </h2>
            <p>
              We may terminate or suspend your access to the App at any time, with or without cause or notice, including for violations of these Terms or our content policies. Upon termination, your right to use the App will immediately cease. Unused gems are non-refundable upon termination. You may stop using the App and delete it from your device at any time. Sections of these Terms that by their nature should survive termination will survive, including ownership provisions, warranty disclaimers, and limitations of liability.
            </p>
          </section>

          {/* Changes to Terms */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Changes to These Terms
            </h2>
            <p>
              We may update these Terms from time to time. When we do, we will revise the &ldquo;Effective Date&rdquo; at the top of this page. Your continued use of the App after any changes constitutes acceptance of the updated Terms. We encourage you to review these Terms periodically.
            </p>
          </section>

          {/* Governing Law */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Governing Law
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to its conflict of law provisions.
            </p>
          </section>

          {/* Contact */}
          <section>
            <h2 className="font-serif text-2xl text-bark-600 mb-4">
              Contact Us
            </h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <div className="mt-4 bg-cream-200/50 rounded-xl p-6 text-sm">
              <p className="font-medium text-bark-600">BloomWave</p>
              <p className="mt-1">
                Email:{' '}
                <a
                  href="mailto:chibijumpstore@gmail.com"
                  className="text-forest-500 hover:text-forest-600 underline underline-offset-2 transition-colors"
                >
                  chibijumpstore@gmail.com
                </a>
              </p>
              <p className="mt-1">
                Website:{' '}
                <a
                  href="https://bloomwave.app"
                  className="text-forest-500 hover:text-forest-600 underline underline-offset-2 transition-colors"
                >
                  bloomwave.app
                </a>
              </p>
            </div>
          </section>
        </div>
      </article>
    </div>
  )
}
